server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
